_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: d10f3868-df73-4822-a6a2-ba25dc4ca8d2
name: 'Local Employee Management Portal'
mail: skfaizannasir21@gmail.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node/134
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
